### ISSUE TITLE
Afbeelding mist voor functies.tex

### ISSUE THREAD

**Issue by KingInktvis** [bart314/ReaderML#1]
Op regel  17 van functions.tex wordt een afbeelding genaamd functie gebruikt die niet bestaat.
Lualatex error:
`warning  (pdf backend): ignoring duplicate destination with the name 'page.1'
[1]) (./functies.tex(load luc: /home/rik/.texlive2018/texmf-var/luatex-cache/ge
neric/fonts/otl/lmroman7-regular.luc)(load luc: /home/rik/.texlive2018/texmf-va
r/luatex-cache/generic/fonts/otl/lmroman5-regular.luc)

! LaTeX Error: File `functie' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.17 ...includegraphics[width=.5\textwidth]{functie}
`

**Comment by bart314** [comment]
Plaatje stond in de verkeerde directory en was niet ingecheckt.
